import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/layouts/navbar/Navbar";
import Sidebar from "@/components/layouts/sidebar/Sidebar";
import Chat from "@/components/layouts/chat/Chat";
import ProtectedRoute from "@/components/auth/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProtectedRoute>
        <div className='flex h-screen bg-white text-black overflow-hidden'>
          <div className='w-64 h-full overflow-y-auto rounded-tr-[40px]'>
            <Sidebar />
          </div>
          <div className='flex-1 h-full overflow-y-auto'>
            <div className='sticky top-0 z-10 bg-white shadow'>
              <Navbar />
            </div>
            <div className='h-full'>{children}</div>
          </div>
          <div className='fixed bottom-[16px] right-[32px]'>
            <Chat/>
          </div>
        </div>
        </ProtectedRoute>
      </body>
    </html>
  );
}
