import type { Metadata } from "next";
import Navbar from "@/components/layouts/navbar/Navbar";
import Sidebar from "@/components/layouts/sidebar/Sidebar";
import Chat from "@/components/layouts/chat/Chat";
import ProtectedRoute from "@/components/auth/ProtectedRoute";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ProtectedRoute>
    <div className='flex h-screen bg-white text-black overflow-hidden'>
      <div className='w-64 h-full overflow-y-auto rounded-tr-[40px]'>
        <Sidebar />
      </div>
      <div className='flex-1 h-full overflow-y-auto'>
        <div className='sticky top-0 z-10 bg-white shadow'>
          <Navbar />
        </div>
        <div className='h-full'>{children}</div>
      </div>
      <div className='fixed bottom-[16px] right-[32px]'>
        <Chat/>
      </div>
    </div>
    </ProtectedRoute>
  );
}
